Repository casper-network/casper-node, pull requests merged in 2020-11, with the labels that each got.

#473 NCTL :: Fixed inline python issue + increased initial balances.
  utils/nctl/sh/utils/misc.sh
Labels: bug, enhancement

#491 NCTL :: updated chainspec.toml
  utils/nctl/templates/chainspec.toml
Labels: bug

#519 1. Replacing WASM paths in setup.sh to continue pointing to assets.
  utils/nctl/sh/assets/setup.sh
Labels: bug

#540 NCTL : ERC-20 + utils refactor
  utils/nctl/sh/assets/dump.sh
  utils/nctl/sh/assets/setup.sh
  utils/nctl/sh/assets/teardown.sh
  utils/nctl/sh/contracts/erc20/do_approve.sh
  utils/nctl/sh/contracts/erc20/do_fund_users.sh
  utils/nctl/sh/contracts/erc20/do_install.sh
  utils/nctl/sh/contracts/erc20/do_transfer.sh
  utils/nctl/sh/contracts/erc20/recipe.md
  utils/nctl/sh/contracts/erc20/utils.sh
  utils/nctl/sh/contracts/erc20/view_balances.sh
  utils/nctl/sh/contracts/erc20/view_details.sh
  utils/nctl/sh/generators/wg_100.sh
  utils/nctl/sh/generators/wg_101.sh
  utils/nctl/sh/generators/wg_110.sh
  utils/nctl/sh/generators/wg_200.sh
  utils/nctl/sh/generators/wg_201.sh
  utils/nctl/sh/generators/wg_210.sh
  utils/nctl/sh/generators/wg_211.sh
  utils/nctl/sh/node/interactive.sh
  utils/nctl/sh/node/log_reset.sh
  utils/nctl/sh/node/restart.sh
  utils/nctl/sh/node/start.sh
  utils/nctl/sh/node/status.sh
  utils/nctl/sh/node/stop.sh
  utils/nctl/sh/node/toggle.sh
  utils/nctl/sh/utils/misc.sh
  utils/nctl/sh/utils/queries.sh
  utils/nctl/sh/utils/set_aliases.sh
  utils/nctl/sh/views/view_chain_account.sh
  utils/nctl/sh/views/view_chain_account_balance.sh
  utils/nctl/sh/views/view_chain_auction_info.sh
  utils/nctl/sh/views/view_chain_block.sh
  utils/nctl/sh/views/view_chain_deploy.sh
  utils/nctl/sh/views/view_chain_spec.sh
  utils/nctl/sh/views/view_chain_spec_accounts.sh
  utils/nctl/sh/views/view_chain_state_root_hash.sh
  utils/nctl/sh/views/view_faucet_account.sh
  utils/nctl/sh/views/view_faucet_account_balance.sh
  utils/nctl/sh/views/view_faucet_account_hash.sh
  utils/nctl/sh/views/view_faucet_account_key.sh
  utils/nctl/sh/views/view_faucet_secret_key_path.sh
  utils/nctl/sh/views/view_node_config.sh
  utils/nctl/sh/views/view_node_log.sh
  utils/nctl/sh/views/view_node_metrics.sh
  utils/nctl/sh/views/view_node_peers.sh
  utils/nctl/sh/views/view_node_status.sh
  utils/nctl/sh/views/view_node_storage.sh
  utils/nctl/sh/views/view_user_account.sh
  utils/nctl/sh/views/view_user_account_balance.sh
  utils/nctl/sh/views/view_user_account_hash.sh
  utils/nctl/sh/views/view_user_account_key.sh
  utils/nctl/sh/views/view_user_secret_key_path.sh
  utils/nctl/sh/views/view_validator_account.sh
  utils/nctl/sh/views/view_validator_account_balance.sh
  utils/nctl/sh/views/view_validator_account_hash.sh
  utils/nctl/sh/views/view_validator_account_key.sh
  utils/nctl/sh/views/view_validator_secret_key_path.sh
Labels: enhancement

#544 Disable `WRITE_MAP` on Mac OS X
  node/src/components/storage.rs
Labels: bug

#573 NCTL : minor enhancements
  utils/nctl/sh/assets/setup_supervisord.sh
  utils/nctl/sh/node/interactive.sh
  utils/nctl/sh/utils.sh
  utils/nctl/sh/views/view_chain_account_balance.sh
Labels: bug, enhancement
