Repository casper-network/casper-node, pull requests merged in 2021-02, with the labels that each got.

#849 NO-TICKET: update RPC server
  node/src/components/rpc_server/http_server.rs
  node/src/components/rpc_server/rpcs.rs
Labels: release blocker

#851 NO-TICKET: replace yamux with mplex
  node/src/components/network.rs
  node/src/components/network/tests_bulk_gossip.rs
Labels: release notes

#850 Cleaning up and simplifying
  README.md
Labels: release blocker

#848 EE-1163: Native transfer error charge
  execution_engine/src/core/engine_state/error.rs
  execution_engine/src/core/engine_state/execution_result.rs
  execution_engine/src/core/engine_state/mod.rs
  execution_engine_testing/tests/src/test/regression/ee_1160.rs
  execution_engine_testing/tests/src/test/regression/ee_1163.rs
  execution_engine_testing/tests/src/test/regression/mod.rs
  execution_engine_testing/tests/src/test/wasmless_transfer.rs
Labels: release blocker

#980 NO-TICKET :: NCTL :: Users are delegators
  utils/nctl/activate
  utils/nctl/sh/assets/setup.sh
  utils/nctl/sh/assets/setup_node.sh
  utils/nctl/sh/contracts-kv/do_install.sh
  utils/nctl/sh/utils/constants.sh
Labels: bug
