Repository casper-network/casper-node, pull requests merged in 2021-09, with the labels that each got.

#1990 Support PublicKey, AccountHash or URef as Client Transfer Target
  client/CHANGELOG.md
  client/lib/deploy.rs
  client/lib/lib.rs
  client/lib/parsing.rs
  client/src/deploy/transfer.rs
Labels: release blocker

#2078 Add `read_trie` rpc and state download tool
  Cargo.lock
  Cargo.toml
  client/lib/validation.rs
  execution_engine/src/core/engine_state/mod.rs
  execution_engine/src/storage/global_state/in_memory.rs
  execution_engine/src/storage/global_state/lmdb.rs
  execution_engine/src/storage/global_state/mod.rs
  node/CHANGELOG.md
  node/src/components/contract_runtime.rs
  node/src/components/fetcher.rs
  node/src/components/rpc_server/http_server.rs
  node/src/components/rpc_server/rpcs.rs
  node/src/components/rpc_server/rpcs/state.rs
  node/src/effect.rs
  node/src/effect/requests.rs
  node/src/types/block.rs
  node/src/types/json_compatibility.rs
  node/src/types/json_compatibility/stored_value.rs
  resources/test/rpc_schema_hashing_V1.json
  resources/test/rpc_schema_hashing_V2.json
  resources/test/sse_data_schema.json
  types/src/key.rs
  types/src/lib.rs
  utils/retrieve-state/.gitignore
  utils/retrieve-state/Cargo.toml
  utils/retrieve-state/src/lib.rs
  utils/retrieve-state/src/main.rs
Labels: release blocker, node

#2099 Set enable_manual_sync to false by default
  node/src/components/contract_runtime/config.rs
  resources/local/config.toml
  resources/production/config-example.toml
  utils/nctl/sh/scenarios/configs/bond_its.config.toml
  utils/nctl/sh/scenarios/configs/gov96.config.toml
  utils/nctl/sh/scenarios/configs/itst13.config.toml
Labels: release blocker

#1854 GH-1764: Add docs to the core modules.
  execution_engine/CHANGELOG.md
  execution_engine/src/core.rs
  execution_engine/src/core/engine_state/balance.rs
  execution_engine/src/core/engine_state/deploy_item.rs
  execution_engine/src/core/engine_state/engine_config.rs
  execution_engine/src/core/engine_state/era_validators.rs
  execution_engine/src/core/engine_state/error.rs
  execution_engine/src/core/engine_state/executable_deploy_item.rs
  execution_engine/src/core/engine_state/execute_request.rs
  execution_engine/src/core/engine_state/execution_effect.rs
  execution_engine/src/core/engine_state/execution_result.rs
  execution_engine/src/core/engine_state/genesis.rs
  execution_engine/src/core/engine_state/get_bids.rs
  execution_engine/src/core/engine_state/mod.rs
  execution_engine/src/core/engine_state/op.rs
  execution_engine/src/core/engine_state/query.rs
  execution_engine/src/core/engine_state/run_genesis_request.rs
  execution_engine/src/core/engine_state/step.rs
  execution_engine/src/core/engine_state/system_contract_cache.rs
  execution_engine/src/core/engine_state/transfer.rs
  execution_engine/src/core/engine_state/upgrade.rs
  execution_engine/src/core/execution/address_generator.rs
  execution_engine/src/core/execution/error.rs
  execution_engine/src/core/execution/executor.rs
  execution_engine/src/core/execution/mod.rs
  execution_engine/src/core/resolvers/error.rs
  execution_engine/src/core/resolvers/memory_resolver.rs
  execution_engine/src/core/resolvers/mod.rs
  execution_engine/src/core/resolvers/v1_function_index.rs
  execution_engine/src/core/runtime/mod.rs
  execution_engine/src/core/runtime_context/mod.rs
  execution_engine/src/core/tracking_copy/mod.rs
  execution_engine/src/lib.rs
  execution_engine/src/shared.rs
  execution_engine_testing/test_support/src/internal/wasm_test_builder.rs
  execution_engine_testing/test_support/src/lib.rs
  node/src/components/rpc_server/rpcs/state.rs
  node/src/effect/requests.rs
  node/src/reactor/participating/tests.rs
  resources/test/rpc_schema_hashing_V1.json
  resources/test/rpc_schema_hashing_V2.json
  resources/test/sse_data_schema.json
  smart_contracts/contract/src/lib.rs
  types/src/contracts.rs
  types/src/motes.rs
Labels: execution engine

#2081 Expand Deploy Acceptor
  execution_engine/src/core/engine_state/executable_deploy_item.rs
  execution_engine/src/core/engine_state/mod.rs
  node/src/components/deploy_acceptor.rs
  node/src/components/deploy_acceptor/event.rs
  node/src/components/deploy_acceptor/tests.rs
  node/src/components/fetcher/tests.rs
  node/src/components/gossiper/tests.rs
  node/src/effect.rs
  node/src/reactor/joiner.rs
  node/src/reactor/participating.rs
  node/src/types.rs
  node/src/types/deploy.rs
  types/src/account.rs
Labels: release blocker

#2126 Fix bug in Deploy acceptor
  execution_engine/src/core/engine_state/transfer.rs
  node/src/components/deploy_acceptor.rs
  node/src/components/deploy_acceptor/tests.rs
  node/src/types/deploy.rs
Labels: release blocker

#2129 Increase price of wasmless transfer
  execution_engine/CHANGELOG.md
  execution_engine/src/shared/system_config.rs
  resources/local/chainspec.toml.in
  resources/production/chainspec.toml
  resources/test/valid/0_9_0/chainspec.toml
  resources/test/valid/0_9_0_unordered/chainspec.toml
  resources/test/valid/1_0_0/chainspec.toml
  utils/nctl/sh/scenarios/chainspecs/bond_its.chainspec.toml.in
  utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in
  utils/nctl/sh/scenarios/chainspecs/itst14.chainspec.toml.in
Labels: release blocker

#2131 Perform account checks on deploys from clients only.
  Cargo.lock
  node/src/components/deploy_acceptor.rs
  node/src/components/deploy_acceptor/tests.rs
Labels: release blocker

#1995 Archival Sync
  node/CHANGELOG.md
  node/src/components/contract_runtime.rs
  node/src/components/linear_chain_sync/error.rs
  node/src/components/linear_chain_sync/operations.rs
  node/src/components/storage.rs
  node/src/effect.rs
  node/src/effect/requests.rs
  node/src/reactor/initializer.rs
  node/src/reactor/joiner.rs
  node/src/reactor/participating.rs
  node/src/reactor/participating/config.rs
  node/src/reactor/participating/error.rs
  node/src/testing/multi_stage_test_reactor.rs
  node/src/testing/multi_stage_test_reactor/test_chain.rs
  node/src/types/node_config.rs
  resources/local/config.toml
  resources/production/config-example.toml
  utils/nctl/sh/scenarios/configs/bond_its.config.toml
  utils/nctl/sh/scenarios/configs/gov96.config.toml
  utils/nctl/sh/scenarios/configs/itst13.config.toml
Labels: fast-sync
