Repository casper-network/casper-node, pull requests merged in 2021-11, with the labels that each got.

#2308 Fix invalid state batch sync condition
  node/src/components/consensus/protocols/highway.rs
Labels: release blocker

#2283 GH-2280: Fix misleading host functions gas charges
  Cargo.lock
  execution_engine/src/core/runtime/externals.rs
  execution_engine/src/core/runtime/host_function_flag.rs
  execution_engine/src/core/runtime/mod.rs
  execution_engine/src/shared/host_function_costs.rs
  execution_engine_testing/tests/src/test/regression/gh_2280.rs
  execution_engine_testing/tests/src/test/regression/mod.rs
  resources/local/chainspec.toml.in
  resources/production/chainspec.toml
  smart_contracts/contracts/test/gh-2280-regression-call/Cargo.toml
  smart_contracts/contracts/test/gh-2280-regression-call/src/main.rs
  smart_contracts/contracts/test/gh-2280-regression/Cargo.toml
  smart_contracts/contracts/test/gh-2280-regression/src/main.rs
  utils/nctl/sh/scenarios/chainspecs/bond_its.chainspec.toml.in
  utils/nctl/sh/scenarios/chainspecs/itst13.chainspec.toml.in
  utils/nctl/sh/scenarios/chainspecs/itst14.chainspec.toml.in
Labels: release blocker

#2322 Port history from casper-engine-test-support repo
  Cargo.lock
  ci/casper_updater/src/regex_data.rs
  execution_engine/Cargo.toml
  execution_engine_testing/cargo_casper/src/common.rs
  execution_engine_testing/test_support/CHANGELOG.md
  execution_engine_testing/test_support/Cargo.toml
  execution_engine_testing/test_support/src/lib.rs
  execution_engine_testing/test_support/src/utils.rs
  hashing/Cargo.toml
  node/Cargo.toml
  types/Cargo.toml
  utils/dry-run-deploys/Cargo.toml
  utils/validation/Cargo.toml
  utils/validation/src/main.rs
Labels: release blocker

#2331 Reject expired deploys sent from a client
  node/src/components/deploy_acceptor.rs
  node/src/components/deploy_acceptor/tests.rs
  node/src/types/deploy.rs
Labels: bug, release blocker

#2279 Backport minor changes from `feat-fast-sync`.
  node/src/components/consensus.rs
  node/src/components/consensus/era_supervisor.rs
  node/src/components/rpc_server/rpcs/chain.rs
  node/src/components/small_network/tests.rs
  node/src/reactor/participating.rs
  node/src/reactor/participating/tests.rs
  node/src/types/block.rs
Labels: fast-sync

#2341 Only upgrade after switch block is fully signed and stored.
  node/src/components/consensus/era_supervisor.rs
  node/src/components/linear_chain.rs
  node/src/components/linear_chain/event.rs
  node/src/components/linear_chain/state.rs
  node/src/components/linear_chain_sync.rs
  node/src/components/linear_chain_sync/operations.rs
  node/src/reactor/participating.rs
Labels: fast-sync

#2391 Reimplement `ToBytes` for some of the most frequently used types.
  types/src/account.rs
  types/src/account/account_hash.rs
  types/src/account/action_thresholds.rs
  types/src/account/associated_keys.rs
  types/src/account/weight.rs
  types/src/bytesrepr.rs
  types/src/contract_wasm.rs
  types/src/contracts.rs
  types/src/crypto/asymmetric_key.rs
  types/src/deploy_info.rs
  types/src/key.rs
  types/src/protocol_version.rs
  types/src/system/auction/bid/mod.rs
  types/src/system/auction/bid/vesting.rs
  types/src/system/auction/delegator.rs
  types/src/system/auction/era_info.rs
  types/src/transfer.rs
  types/src/uref.rs
Labels: optimization

#2414 Add `write_bytes` method on `ToBytes` trait that serializes value without intermediate allocations.
  execution_engine/src/core/runtime_context/dictionary.rs
  execution_engine/src/storage/trie/gens.rs
  execution_engine/src/storage/trie/mod.rs
  execution_engine/src/storage/trie/tests.rs
  execution_engine/src/storage/trie_store/tests/proptests.rs
  hashing/src/lib.rs
  types/src/access_rights.rs
  types/src/account.rs
  types/src/account/account_hash.rs
  types/src/account/action_thresholds.rs
  types/src/account/associated_keys.rs
  types/src/account/weight.rs
  types/src/bytesrepr.rs
  types/src/bytesrepr/bytes.rs
  types/src/cl_value.rs
  types/src/contract_wasm.rs
  types/src/contracts.rs
  types/src/crypto/asymmetric_key.rs
  types/src/deploy_info.rs
  types/src/era_id.rs
  types/src/key.rs
  types/src/protocol_version.rs
  types/src/stored_value.rs
  types/src/system/auction/bid/mod.rs
  types/src/system/auction/bid/vesting.rs
  types/src/system/auction/delegator.rs
  types/src/system/auction/era_info.rs
  types/src/system/auction/unbonding_purse.rs
  types/src/transfer.rs
  types/src/uref.rs
Labels: optimization
