Repository casper-network/casper-node, pull requests merged in 2021-01, with the labels that each got.

#732 NCTL :: Docs update plus minor fix.
  utils/nctl/activate
  utils/nctl/docs/setup.md
Labels: bug, documentation

#741 NCTL :: Join & Leave updates
  utils/nctl/activate
  utils/nctl/docs/commands-ctl.md
  utils/nctl/sh/assets/setup.sh
  utils/nctl/sh/node/clean.sh
  utils/nctl/sh/node/clean_logs.sh
  utils/nctl/sh/node/join.sh
  utils/nctl/sh/node/leave.sh
  utils/nctl/sh/node/restart.sh
  utils/nctl/sh/node/start.sh
  utils/nctl/sh/node/start_after_n_blocks.sh
  utils/nctl/sh/node/start_after_n_eras.sh
  utils/nctl/sh/node/svc_supervisord.sh
  utils/nctl/sh/utils/paths.sh
  utils/nctl/sh/views/view_node_event_stream.sh
  utils/nctl/sh/views/view_node_metrics.sh
  utils/nctl/sh/views/view_node_peers.sh
  utils/nctl/sh/views/view_node_status.sh
Labels: enhancement

#824 NDRS-805: Fix multisig
  grpc/test_support/src/internal/deploy_item_builder.rs
  grpc/tests/src/test/contract_api/account/authorized_keys.rs
  node/src/types/deploy.rs
Labels: release blocker

#826 NO-TICKET: enable libp2p component by default
  node/src/components/network.rs
  node/src/components/network/tests.rs
  node/src/components/small_network.rs
  node/src/components/small_network/tests.rs
  node/src/reactor/joiner.rs
  node/src/reactor/validator.rs
  resources/maintainer_scripts/casper_node/casper-node.service
Labels: release blocker

#805 NDRS-773/yamux buffer size, cannot reproduce
  node/src/components.rs
  node/src/components/collector.rs
  node/src/components/network.rs
  node/src/components/network/behavior.rs
  node/src/components/network/event.rs
  node/src/components/network/tests_bulk_gossip.rs
  node/src/logging.rs
Labels: release blocker
