Repository casper-network/casper-node, pull requests merged in 2021-05, with the labels that each got.

#1434 STS-100 :: Protocol upgrade scenario test for CI/CD
  .gitignore
  utils/nctl/activate
  utils/nctl/sh/assets/dump.sh
  utils/nctl/sh/assets/setup.sh
  utils/nctl/sh/assets/setup_from_stage.sh
  utils/nctl/sh/assets/setup_shared.sh
  utils/nctl/sh/assets/upgrade.sh
  utils/nctl/sh/assets/upgrade_from_stage.sh
  utils/nctl/sh/contracts-auction/do_bid.sh
  utils/nctl/sh/contracts-transfers/do_dispatch_native.sh
  utils/nctl/sh/contracts-transfers/do_dispatch_wasm.sh
  utils/nctl/sh/node/join.sh
  utils/nctl/sh/node/svc_supervisord.sh
  utils/nctl/sh/scenarios-upgrades/upgrade_scenario_01.sh
  utils/nctl/sh/scenarios-upgrades/upgrade_scenario_02.sh
  utils/nctl/sh/staging/build.sh
  utils/nctl/sh/staging/build_from_settings.sh
  utils/nctl/sh/staging/set_from_commit.sh
  utils/nctl/sh/staging/set_from_local.sh
  utils/nctl/sh/staging/set_from_remote.sh
  utils/nctl/sh/staging/set_remote.sh
  utils/nctl/sh/staging/set_remotes.sh
  utils/nctl/sh/staging/settings-template.txt
  utils/nctl/sh/utils/blocking.sh
  utils/nctl/sh/utils/infra.sh
  utils/nctl/sh/utils/os.sh
  utils/nctl/sh/utils/paths.sh
  utils/nctl/sh/utils/queries.sh
  utils/nctl/sh/views/view_node_config.sh
Labels: bug

#1493 Revert NDRS-1082
  node/src/components/consensus/consensus_protocol.rs
  node/src/components/storage.rs
  node/src/crypto/hash.rs
  node/src/types/block.rs
  node/src/types/deploy.rs
  utils/nctl/sh/scenarios/sync_upgrade_test.sh
Labels: release blocker

#1495 Revert "Group restriction fix"
  Cargo.lock
  execution_engine/src/core/engine_state/genesis.rs
  execution_engine/src/core/execution/error.rs
  execution_engine/src/core/runtime/mod.rs
  execution_engine_testing/tests/Cargo.toml
  execution_engine_testing/tests/src/test/regression/gh_1470.rs
  execution_engine_testing/tests/src/test/regression/mod.rs
  smart_contracts/contracts/test/do-nothing-stored-upgrader/src/main.rs
  smart_contracts/contracts/test/do-nothing-stored/src/main.rs
  smart_contracts/contracts/test/gh-1470-regression-call/Cargo.toml
  smart_contracts/contracts/test/gh-1470-regression-call/src/bin/main.rs
  smart_contracts/contracts/test/gh-1470-regression-call/src/lib.rs
  smart_contracts/contracts/test/gh-1470-regression/Cargo.toml
  smart_contracts/contracts/test/gh-1470-regression/src/bin/main.rs
  smart_contracts/contracts/test/gh-1470-regression/src/lib.rs
  smart_contracts/contracts/test/transfer-purse-to-accounts-stored/src/main.rs
  smart_contracts/contracts_as/client/undelegate/assembly/index.ts
  smart_contracts/contracts_as/test/do-nothing-stored-upgrader/assembly/index.ts
  smart_contracts/contracts_as/test/do-nothing-stored/assembly/index.ts
  types/src/contracts.rs
  types/src/runtime_args.rs
Labels: release blocker

#1488 OP-2028: nctl upgrades in ci
  .drone.yml
  ci/nctl_upgrade.sh
  utils/nctl/sh/assets/setup_shared.sh
  utils/nctl/sh/scenarios-upgrades/upgrade_scenario_01.sh
  utils/nctl/sh/staging/set_remote.sh
  utils/nctl/sh/staging/set_remotes.sh
  utils/nctl/sh/utils/queries.sh
Labels: nctl, release blocker
